<?php
declare(strict_types=1);
if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

// Keep the browser entry point compatible with file previews and ordinary hosting.
// Rebuild with: php tests/build-browser.php
$root = dirname(__DIR__);
$cart = file_get_contents($root . '/assets/js/cart.mjs');
$app = file_get_contents($root . '/assets/js/app.mjs');
$catalog = json_decode(file_get_contents($root . '/assets/data/catalog.json'), true, 32, JSON_THROW_ON_ERROR);
$discounts = json_decode(file_get_contents($root . '/assets/data/discount-policy.json'), true, 16, JSON_THROW_ON_ERROR);
$cart = preg_replace('/^export /m', '', $cart);
$app = preg_replace('/^import .*;\R/m', '', $app);
$header = "// Generated by php tests/build-browser.php. Edit app.mjs, cart.mjs or catalog.json, then rebuild.\n";
$bundle = $header . "(async function () {\n'use strict';\n\nconst EMBEDDED_CATALOG = "
    . json_encode($catalog, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR)
    . ";\n\nconst EMBEDDED_DISCOUNT_POLICY = " . json_encode($discounts, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR) . ";\n\n" . $cart . "\n" . $app . "\n})();\n";
file_put_contents($root . '/assets/js/app.js', $bundle);
echo "Built assets/js/app.js with " . count($catalog) . " catalogue items.\n";
